# Generated by Django 5.0.6 on 2026-07-11 08:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10)),
                ('source_type', models.CharField(choices=[('upload', 'File upload'), ('url', 'Remote URL'), ('webcam', 'Live webcam')], default='upload', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('verdict', models.CharField(blank=True, choices=[('real', 'Real'), ('fake', 'Fake'), ('uncertain', 'Uncertain')], max_length=10, null=True)),
                ('confidence', models.FloatField(blank=True, help_text='0-100 confidence that the media is FAKE', null=True)),
                ('model_used', models.CharField(default='truthlens-fusion-v1', max_length=100)),
                ('explanation', models.TextField(blank=True, default='')),
                ('heatmap', models.ImageField(blank=True, null=True, upload_to='heatmaps/%Y/%m/%d/')),
                ('ensemble_results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='detection.scan')),
            ],
        ),
    ]
