# Generated by Django 5.0.6 on 2026-07-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='processing_time_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scan',
            name='signal_breakdown',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
